services:
  api:
    build:
      context: .
      dockerfile: Containerfile.dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - API_KEY=123456
      - DSN=host=db user=postgres password=postgres dbname=postgres sslmode=disable
    volumes:
      - cache:/root/.cache/go-build
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s
      start_interval: 3s


volumes:
  cache:
  db:

